/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartbinapp;

/**
 *
 * @author ikram
 */
public class SmartBinGUI extends javax.swing.JFrame {

    /**
     * Creates new form GuiApp
     */
    public SmartBinGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPNL = new javax.swing.JPanel();
        exitBTN = new javax.swing.JButton();
        exitLBL = new javax.swing.JLabel();
        editBTN = new javax.swing.JButton();
        editLBL = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        addLBL = new javax.swing.JLabel();
        linePNL = new javax.swing.JPanel();
        cardPNL = new javax.swing.JPanel();
        editPNL = new javax.swing.JPanel();
        editTitle = new javax.swing.JLabel();
        addPNL = new javax.swing.JPanel();
        addTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navPNL.setBackground(new java.awt.Color(0, 0, 0));
        navPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navPNL.setForeground(new java.awt.Color(255, 255, 255));

        exitBTN.setBackground(new java.awt.Color(0, 153, 255));
        exitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-icon.png"))); // NOI18N
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        exitLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitLBL.setForeground(new java.awt.Color(255, 255, 255));
        exitLBL.setText("Exit");

        editBTN.setBackground(new java.awt.Color(0, 153, 255));
        editBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.png"))); // NOI18N
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        editLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editLBL.setForeground(new java.awt.Color(255, 255, 255));
        editLBL.setText("Edit");

        addBTN.setBackground(new java.awt.Color(0, 153, 255));
        addBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        addLBL.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        addLBL.setForeground(new java.awt.Color(255, 255, 255));
        addLBL.setText("Add Queue/Stack");

        javax.swing.GroupLayout navPNLLayout = new javax.swing.GroupLayout(navPNL);
        navPNL.setLayout(navPNLLayout);
        navPNLLayout.setHorizontalGroup(
            navPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPNLLayout.createSequentialGroup()
                .addGroup(navPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(navPNLLayout.createSequentialGroup()
                        .addGroup(navPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(navPNLLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(editLBL))
                            .addComponent(editBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(navPNLLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(exitLBL))
                            .addGroup(navPNLLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addLBL)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        navPNLLayout.setVerticalGroup(
            navPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editLBL)
                .addGap(18, 18, 18)
                .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addLBL)
                .addGap(18, 18, 18)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLBL)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(navPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 490));

        linePNL.setBackground(new java.awt.Color(0, 204, 204));
        linePNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        linePNL.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout linePNLLayout = new javax.swing.GroupLayout(linePNL);
        linePNL.setLayout(linePNLLayout);
        linePNLLayout.setHorizontalGroup(
            linePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        linePNLLayout.setVerticalGroup(
            linePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        getContentPane().add(linePNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 489));

        cardPNL.setBackground(new java.awt.Color(0, 102, 102));
        cardPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cardPNL.setForeground(new java.awt.Color(255, 255, 255));
        cardPNL.setLayout(new java.awt.CardLayout());

        editPNL.setBackground(new java.awt.Color(0, 102, 102));
        editPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editPNL.setForeground(new java.awt.Color(255, 255, 255));
        editPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editTitle.setForeground(new java.awt.Color(255, 255, 255));
        editTitle.setText("Smart Bin Management");
        editPNL.add(editTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        cardPNL.add(editPNL, "card2");

        addPNL.setBackground(new java.awt.Color(0, 102, 102));
        addPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addPNL.setForeground(new java.awt.Color(255, 255, 255));
        addPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addTitle.setForeground(new java.awt.Color(255, 255, 255));
        addTitle.setText("Queue and Stack Manager");
        addPNL.add(addTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        cardPNL.add(addPNL, "card3");

        getContentPane().add(cardPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 560, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        // TODO add your handling code here:
        editPNL.setVisible(true);
        addPNL.setVisible(false);
    }//GEN-LAST:event_editBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        editPNL.setVisible(false);
        addPNL.setVisible(true);
    }//GEN-LAST:event_addBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartBinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartBinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartBinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartBinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartBinGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel addLBL;
    private javax.swing.JPanel addPNL;
    private javax.swing.JLabel addTitle;
    private javax.swing.JPanel cardPNL;
    private javax.swing.JButton editBTN;
    private javax.swing.JLabel editLBL;
    private javax.swing.JPanel editPNL;
    private javax.swing.JLabel editTitle;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel exitLBL;
    private javax.swing.JPanel linePNL;
    private javax.swing.JPanel navPNL;
    // End of variables declaration//GEN-END:variables
}
